name: Build & deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
        matrix:
            node-version: [20.x]

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install rsync
        run: sudo apt install rsync

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
            node-version: ${{ matrix.node-version }}

      - name: Install pnpm
        run: npm i -g pnpm

      - name: Install dependencies
        run: |
          pnpm install

      - name: Build project
        run: |
          pnpm run build

      - name: Deploy build
        uses: easingthemes/ssh-deploy@v2.2.11
        with:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
          REMOTE_HOST: smertos.xyz
          REMOTE_USER: smertos
          SOURCE: dist/**
          TARGET: /var/www/smertos.xyz/
